Second srag and drop
tyrell-x/apollofy-client pull request #79
Opened 2021-05-09 09:49 UTC by Leyber91

- Drag and Drop to change manually the playlist order on display effectively working.
- Manual order reflects on player queue
- Mock Drag And Drop eliminated from home

2021-05-09 12:56 UTC, CCPablo commented on src/components/AddToPlaylist/AddToPlaylist.js
> +import "./AddToPlaylist.scss";
Esto forma parte de otra tarea, no?

2021-05-09 15:40 UTC, CCPablo commented on src/redux/cards/card-actions.js
> +import * as cardList from "./track-types";
Toda esta carpeta de cards en redux que es una copy paste de la carpeta de tracks por qué?

2021-05-09 15:50 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +    updatePlaylist(items);
Está haciendo esta función efecto? No debería de ser dispatch(updatePlaylist(items))? Pasa lo mismo con fetchPlaylists de la línea 57

2021-05-09 15:50 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +  const [tracksPlaylist, updatePlaylistOrder] = useState(tracks);
La idea de utilizar redux es no tener que tener el estado local para el orden, y usar directamente el cambio en la base de datos a partir de redux. 

Por otra parte, solo funciona el reordenamiento una vez, porque la base de la reordenación estás cogiéndola de la variable tracks que es la que llega inicialmente.

2021-05-09 15:52 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +                // DIV OF THE TRACK
El elemento a reordenar, cuando se reordena, queda en una posición extraña debido a unos conflictos con los márgenes

2021-05-09 15:52 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +      <h2>The list</h2>
No formaba parte del diseño

2021-05-09 15:53 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +    console.log(items)
Acuérdate de limpiar los console logs y comentarios antes de subir una pull requests. Si no, te lo van a estar recordando siempre :D

2021-05-09 15:56 UTC, CCPablo requested changes
Me cuesta entender que cambios son los que aplican a tu tarea, creía que ya vimos las consecuencias de mergear entre ramas de distintas tareas sin terminar jajaja

2021-05-09 15:58 UTC, CCPablo commented on src/pages/Playlist/Playlist.js
> +    updatePlaylist(items);
Por otra parte, este fetchPlaylists no haría falta, ya que la información ya la tienes y no tienes que hacer una petición nueva que te traiga la información de esta playlist, y menos de todas las playlists

2021-05-10 15:33 UTC, Leyber91 commented on src/redux/cards/card-actions.js
> +import * as cardList from "./track-types";
Carpeta ya eliminada debido a que era codigo sin usar.

2021-05-10 15:33 UTC, Leyber91 commented on src/components/AddToPlaylist/AddToPlaylist.js
> +import "./AddToPlaylist.scss";
Rama mergeada por error antes de pasar por main, conflictos ya solucionados.

2021-05-10 15:34 UTC, Leyber91 commented on src/pages/Playlist/Playlist.js
> +      <h2>The list</h2>
Era simplemente a modo de diferenciar, ahora queda eliminado en el último quick fix commit style.

2021-05-10 15:38 UTC, Leyber91 commented on src/pages/Playlist/Playlist.js
> +    console.log(items)
Console logs eliminados. Gracias ;).

2021-05-10 17:31 UTC, CCPablo approved these changes
Perfected

2021-05-10 17:32 UTC, merged